export const data = [
    {
      "id": 1,
      "Grupo": "Hospitalización",
      "Subgrupo": "Hospitalización",
      "Nombre": "General adultos",
      "Descripcion": "Habitaciones compartidas e individuales para el cuidado de la salud de los pacientes pacientes adultos.",
      "Portal": "",
      "Horario_atencion": null,
      "Horario_visitas": "10:00 am. a 8:00 p.m.",
      "Ubicacion": "Torre A y Torre B"
    },
    {
      "id": 2,
      "Grupo": "Hospitalización",
      "Subgrupo": "Hospitalización",
      "Nombre": "General pediátrica",
      "Descripcion": "Habitaciones compartidas e individuales para el cuidado de la salud de los pacientes pacientes pediátricos (1 mes a 15 años de vida)",
      "Portal": "https://www.hptu.org.co/hospitalización-pediátrica-general.html",
      "Horario_atencion": null,
      "Horario_visitas": "10:00 am. a 8:00 p.m.",
      "Ubicacion": "Torre A Piso 9"
    },
    {
      "id": 3,
      "Grupo": "Hospitalización",
      "Subgrupo": "Hospitalización",
      "Nombre": "Cuidado intermedio neonatal",
      "Descripcion": "Es una unidad para la atención de pacientes bajo la responsabilidad de un médico especialista en pediatría y sus áreas específicas, se realiza la atención del recién nacido (de menos de 30 días de vida), con patología leve que necesita técnicas especiales de cuidados medios.",
      "Portal": "https://www.hptu.org.co/cuidado-cr%C3%ADtico.html",
      "Horario_atencion": null,
      "Horario_visitas": "7:00 a.m. a 8:00 a.m.. 11:00 a.m. a 12:00 m.. 3:00 p.m. a 4:00 p.m.. 6:00 p.m. a 7:00 p.m.",
      "Ubicacion": "Torre A Piso 8"
    },
    {
      "id": 4,
      "Grupo": "Hospitalización",
      "Subgrupo": "Hospitalización",
      "Nombre": "Cuidado intermedio pediátrico",
      "Descripcion": "Es una unidad para la atención de pacientes bajo la responsabilidad de un médico especialista en pediatría y sus áreas específicas, se realiza la atención del niño (1 mes a 15 años de vida), con patología leve que necesita técnicas especiales de cuidados medios.",
      "Portal": "https://www.hptu.org.co/cuidado-cr%C3%ADtico.html",
      "Horario_atencion": null,
      "Horario_visitas": "7:00 a.m. a 8:00 a.m.. 11:00 a.m. a 12:00 m.. 3:00 p.m. a 4:00 p.m.. 6:00 p.m. a 7:00 p.m.",
      "Ubicacion": "Torre A Piso 8"
    },
    {
      "id": 5,
      "Grupo": "Hospitalización",
      "Subgrupo": "Hospitalización",
      "Nombre": "Cuidado intermedio adultos",
      "Descripcion": "Es una unidad para la atención de pacientes que padecen o pueden padecer, un compromiso severo de sus funciones vitales",
      "Portal": "https://www.hptu.org.co/cuidado-cr%C3%ADtico.html",
      "Horario_atencion": null,
      "Horario_visitas": "7:00 a.m. a 8:00 a.m.. 11:00 a.m. a 12:00 m.. 3:00 p.m. a 4:00 p.m.. 6:00 p.m. a 7:00 p.m.",
      "Ubicacion": "Torre A Piso 7"
    },
    {
      "id": 6,
      "Grupo": "Hospitalización",
      "Subgrupo": "Hospitalización",
      "Nombre": "Cuidado intensivo neonatal",
      "Descripcion": "Es una unidad para la atención de pacientes bajo la responsabilidad de un médico especialista en pediatría y sus áreas específicas, se realiza la atención del recién nacido (de menos de 30 días de vida), con patología médico-quirúrgica, con compromiso vital, que precisa de medios y cuidados especiales de forma continuada.",
      "Portal": "https://www.hptu.org.co/cuidado-cr%C3%ADtico.html",
      "Horario_atencion": null,
      "Horario_visitas": "7:00 a.m. a 8:00 a.m.. 11:00 a.m. a 12:00 m.. 3:00 p.m. a 4:00 p.m.. 6:00 p.m. a 7:00 p.m.",
      "Ubicacion": "Torre A Piso 8"
    },
    {
      "id": 7,
      "Grupo": "Hospitalización",
      "Subgrupo": "Hospitalización",
      "Nombre": "Cuidado intensivo pediátrico",
      "Descripcion": "Es una unidad para la atención de pacientes bajo la responsabilidad de un médico especialista en pediatría y sus áreas específicas, se realiza la atención del niño (1 mes a 15 años devida), con patología médico-quirúrgica, con compromiso vital, que precisa de medios y cuidados especiales de forma continuada.",
      "Portal": "https://www.hptu.org.co/cuidado-cr%C3%ADtico.html",
      "Horario_atencion": null,
      "Horario_visitas": "7:00 a.m. a 8:00 a.m.. 11:00 a.m. a 12:00 m.. 3:00 p.m. a 4:00 p.m.. 6:00 p.m. a 7:00 p.m.",
      "Ubicacion": "Torre A Piso 8"
    },
    {
      "id": 8,
      "Grupo": "Hospitalización",
      "Subgrupo": "Hospitalización",
      "Nombre": "Cuidado intensivo adultos",
      "Descripcion": "Es una unidad para la atención médica intensiva a los pacientes que padecen una situación grave de salud que pone en peligro su vida",
      "Portal": "https://www.hptu.org.co/cuidado-cr%C3%ADtico.html",
      "Horario_atencion": null,
      "Horario_visitas": "7:00 a.m. a 8:00 a.m.. 11:00 a.m. a 12:00 m.. 3:00 p.m. a 4:00 p.m.. 6:00 p.m. a 7:00 p.m.",
      "Ubicacion": "Torre A Piso 4 - Torre B Piso 5"
    },
    {
      "id": 9,
      "Grupo": "Hospitalización",
      "Subgrupo": "Hospitalización",
      "Nombre": "Cuidado básico neonatal",
      "Descripcion": "Habitaciones compartidas e individuales para el cuidado de la salud de los pacientes pacientes neonatos (de menos de 30 días de vida).",
      "Portal": "",
      "Horario_atencion": null,
      "Horario_visitas": "10:00 am. a 8:00 p.m.",
      "Ubicacion": "Torre A Piso 8"
    },
    {
      "id": 10,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Cirugía de cabeza y cuello",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de enfermedades localizadas en cabeza y cuello.",
      "Portal": "https://www.hptu.org.co/subespecialidades-pediátricas.html",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 11,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Cardiovascular",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de los trastornos y enfermedades del sistema cardiocirculatorio.",
      "Portal": "https://www.hptu.org.co/cardiolog%C3%ADa.html",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 12,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "General",
      "Descripcion": "Especialidad quirúrgica que abarca las operaciones del aparato digestivo; incluyendo el tracto gastrointestinal y el sistema hepato-bilio-pancreático, el sistema endocrino; incluyendo las glándulas suprarrenales, tiroides, paratiroides, mama y otras glándulas incluidas en el aparato digestivo.",
      "Portal": "https://www.hptu.org.co/cirug%C3%ADa-general.html",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 13,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Ginecológica",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de enfermedades localizadas en el aparato reproductor femenino",
      "Portal": "",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 14,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Neurológica",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de determinadas enfermedades del sistema nervioso central, periférico y vegetativo",
      "Portal": "",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 15,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Ortopédica",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de las afecciones del sistema musculoesquelético (músculos, articulaciones, ligamentos, tendones, cartílago, huesos).",
      "Portal": "https://www.hptu.org.co/ortopedia.html",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 16,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Oftalmológica",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de enfermedades localizadas en el ojo.",
      "Portal": "",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 17,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Otorrinolaringología (incluye otología y otoneurología)",
      "Descripcion": "Especialidad quirúrgica encargada del manejoe las enfermedades localizadas en el oído. Las vías aéreo-respiratorias superiores: nariz y senos paranasales, faringe y laringe.",
      "Portal": "",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 18,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Oncológica",
      "Descripcion": "Especialidad quirúrgica encargada de hacer el manejo integral de las enfermedades malignas de los diferentes órganos",
      "Portal": "",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 19,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Pediátrica",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de las enfermedades de los niños (0 a 15 años)",
      "Portal": "https://www.hptu.org.co/subespecialidades-pediátricas.html",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 20,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Plástica y estética",
      "Descripcion": "Especialidad quirúrgica que se encarga de la corrección de todo proceso congénito, adquirido, tumoral o simplemente involutivo, que requiera reparación o reposición, o que afecte a la forma y/o función corporal",
      "Portal": "",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 21,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Vascular y angiológica",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de las enfermedades  del aparato circulatorio.",
      "Portal": "",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 22,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Urológica",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de las enferemdades del sistema urinario y genital de hombres y mujeres.",
      "Portal": "https://www.hptu.org.co/urolog%C3%ADa.html",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 23,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Bariátrica",
      "Descripcion": "Especialidad quirúrgica encargada del tratamiento del paciente con obesidad mórbida sin respuesta a otras opciones de manejo.",
      "Portal": "",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 24,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Coloproctológica",
      "Descripcion": "Especialidad quirúrgica encargada  de las enfermedades funcionales y anatómicas del intestino grueso (colon, recto y conducto anal).",
      "Portal": "https://www.hptu.org.co/coloproctolog%C3%ADa.html",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 25,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Ortopédica oncológica",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de pacientes con tumores benignos o malignos localizados en los huesos.",
      "Portal": "https://www.hptu.org.co/subespecialidades-pediátricas.html",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 26,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Hepatobiliar",
      "Descripcion": "Especialidad quirúrgica encargada de las enfermedades del hígado, páncreas y vías biliares.",
      "Portal": "",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 27,
      "Grupo": "Cirugía",
      "Subgrupo": "Trasplantes",
      "Nombre": "Trasplante renal",
      "Descripcion": "Procedimiento que consiste en la implantación de un riñón sano a una persona que padece insuficiencia renal crónica y que puede ser de un donante vivo o de origen cadáver",
      "Portal": "https://hospitalpablotobonuribe.com.co/grupos-estructurados-de-educación/101-educación-a-pacientes/grupos-estructurados-de-educación/495-trasplante-de-órganos-sólidos.html",
      "Horario_atencion": null,
      "Horario_visitas": "Hospitalización general: 10:00 am a 8:00 pm.  Cuidados Intensivos o Especiales: 7-8 am, 11-12 m, 3-4 pm y 6-7 pm",
      "Ubicacion": null
    },
    {
      "id": 28,
      "Grupo": "Cirugía",
      "Subgrupo": "Trasplantes",
      "Nombre": "Trasplante de hígado",
      "Descripcion": "Procedimiento que consiste en la implantación de un hígado enfermo por uno sano.",
      "Portal": "https://hospitalpablotobonuribe.com.co/grupos-estructurados-de-educación/101-educación-a-pacientes/grupos-estructurados-de-educación/495-trasplante-de-órganos-sólidos.html",
      "Horario_atencion": null,
      "Horario_visitas": "Hospitalización general: 10:00 am a 8:00 pm.  Cuidados Intensivos o Especiales: 7-8 am, 11-12 m, 3-4 pm y 6-7 pm",
      "Ubicacion": null
    },
    {
      "id": 29,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "De la mano",
      "Descripcion": "Especialidad quirúrgica encargada  de las enfermedades que puedan producirse en la mano o en las extremidades superiores (comúnmente desde la punta de la mano hasta el hombro)",
      "Portal": "",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 30,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Mama y tumores tejidos blandos",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de enfermedades localizadas en las glándulas mamarias o en todos los tejidos blandos del cuerpo en general como músculos, tejidos subcutáneos y piel.",
      "Portal": "https://www.hptu.org.co/subespecialidades-pediátricas.html",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 31,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "De tórax",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de enfermedades de los distintos órganos contenidos en el tórax con excepción del corazón y los grandes vasos",
      "Portal": "https://www.hptu.org.co/cirug%C3%ADa-de-tórax.html",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 32,
      "Grupo": "Cirugía",
      "Subgrupo": "Cirugía",
      "Nombre": "Gastrointestinal",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de enfermedades del esófago, estómago, duodeno, hígado y vías biliares, vesícula biliar, páncreas, intestino delgado y grueso.",
      "Portal": "",
      "Horario_atencion": null,
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 4"
    },
    {
      "id": 33,
      "Grupo": "Cirugía",
      "Subgrupo": "Trasplantes",
      "Nombre": "Trasplante de intestino",
      "Descripcion": "Procedimiento que se realiza cuando ocurre una falla intestinal como consecuencia de malformaciones congénitas, enfermedades metabólicas, trastornos de absorción o resecciones intestinales.",
      "Portal": "https://hospitalpablotobonuribe.com.co/grupos-estructurados-de-educación/101-educación-a-pacientes/grupos-estructurados-de-educación/495-trasplante-de-órganos-sólidos.html",
      "Horario_atencion": null,
      "Horario_visitas": "Hospitalización general: 10:00 am a 8:00 pm.  Cuidados Intensivos o Especiales: 7-8 am, 11-12 m, 3-4 pm y 6-7 pm",
      "Ubicacion": null
    },
    {
      "id": 34,
      "Grupo": "Cirugía",
      "Subgrupo": "Trasplantes",
      "Nombre": "Trasplante multivisceral",
      "Descripcion": "Procedimiento que se realiza cuando ocurre una falla intestinal como consecuencia de malformaciones congénitas, enfermedades metabólicas, trastornos de absorción o resecciones intestinales.",
      "Portal": "https://hospitalpablotobonuribe.com.co/grupos-estructurados-de-educación/101-educación-a-pacientes/grupos-estructurados-de-educación/495-trasplante-de-órganos-sólidos.html",
      "Horario_atencion": null,
      "Horario_visitas": "Hospitalización general: 10:00 am a 8:00 pm.  Cuidados Intensivos o Especiales: 7-8 am, 11-12 m, 3-4 pm y 6-7 pm",
      "Ubicacion": null
    },
    {
      "id": 35,
      "Grupo": "Cirugía",
      "Subgrupo": "Trasplantes",
      "Nombre": "Trasplante de tejido osteomuscular",
      "Descripcion": "Procedimiento que se realiza para el reemplazo de un tejido osteomuscular dañado por otro sano",
      "Portal": "https://hospitalpablotobonuribe.com.co/grupos-estructurados-de-educación/101-educación-a-pacientes/grupos-estructurados-de-educación/495-trasplante-de-órganos-sólidos.html",
      "Horario_atencion": null,
      "Horario_visitas": "Hospitalización general: 10:00 am a 8:00 pm.  Cuidados Intensivos o Especiales: 7-8 am, 11-12 m, 3-4 pm y 6-7 pm",
      "Ubicacion": null
    },
    {
      "id": 36,
      "Grupo": "Cirugía",
      "Subgrupo": "Trasplantes",
      "Nombre": "Trasplante de progenitores hematopoyéticos",
      "Descripcion": "Procedimiento terapéutico utilizado en tumores malignos o enfermedades de la médula ósea.",
      "Portal": "https://hospitalpablotobonuribe.com.co/grupos-estructurados-de-educación/101-educación-a-pacientes/grupos-estructurados-de-educación/495-trasplante-de-órganos-sólidos.html",
      "Horario_atencion": null,
      "Horario_visitas": "Hospitalización general: 10:00 am a 8:00 pm.  Cuidados Intensivos o Especiales: 7-8 am, 11-12 m, 3-4 pm y 6-7 pm",
      "Ubicacion": null
    },
    {
      "id": 37,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Alergología clínica",
      "Descripcion": "Especialidad médica que trata sobre el conocimiento, diagnóstico y tratamiento de la patología producida por mecanismos de autoinmunidad.",
      "Portal": "https://www.hptu.org.co/subespecialidades-pediátricas.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 38,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Cirugía bariátrica",
      "Descripcion": "Especialidad quirúrgica encargada del tratamiento del paciente con obesidad mórbida sin respuesta a otras opciones de manejo.",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 39,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Cirugia cardiovascular",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de los trastornos y enfermedades del sistema cardiocirculatorio.",
      "Portal": "https://www.hptu.org.co/cardiolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 40,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Cirugia de tórax",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de enfermedades de los distintos órganos contenidos en el tórax con excepción del corazón y los grandes vasos",
      "Portal": "https://www.hptu.org.co/cardiolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 41,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Cirugia general",
      "Descripcion": "Especialidad quirúrgica que abarca las operaciones del aparato digestivo; incluyendo el tracto gastrointestinal y el sistema hepato-bilio-pancreático, el sistema endocrino; incluyendo las glándulas suprarrenales, tiroides, paratiroides, mama y otras glándulas incluidas en el aparato digestivo.",
      "Portal": "https://www.hptu.org.co/cardiolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 42,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Cirugia hígado-vías biliares y páncreas",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de enfermedades del hígado, vías biliares y páncreas",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 43,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Cirugia plástica y estética",
      "Descripcion": "Especialidad quirúrgica cuyo objetivo es mejorar la forma y/o función del organismo, a través del tratamiento de los defectos ocasionados por traumatismos, malformaciones congénitas o extirpaciones por cáncer.",
      "Portal": "https://www.hptu.org.co/subespecialidades-pediátricas.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 44,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Cirugia vascular",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de las afecciones de los vasos del cuerpo (venas y arterias) por fuera del músculo cardíaco",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 45,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Coloproctología",
      "Descripcion": "Especialidad médica que trata el diagnóstico y tratamiento quirúrgico y no quirúrgico de las enfermedades del colon, recto y ano.",
      "Portal": "https://www.hptu.org.co/cirug%C3%ADa-de-tórax.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 46,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Dermatología",
      "Descripcion": "Especialidad médica que trata la estructura y función de la piel, así como de las enfermedades que la afectan, su diagnóstico, prevención y tratamiento",
      "Portal": "https://www.hptu.org.co/cirug%C3%ADa-general.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 47,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Electrofisiología",
      "Descripcion": "Especialidad médica que se ocupa del estudio, diagnóstico y tratamiento de los trastornos del ritmo cardiaco ó arritmias",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 48,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Endocrinología adultos",
      "Descripcion": "Especialidad médica que se ocupa del estudio de las glándulas de secreción interna. Las glándulas endocrinas son órganos que producen sustancias químicas llamadas hormonas que se incorporan al organismo a través del sistema circulatorio",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 49,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Fisiatría",
      "Descripcion": "Especialidad médica que trata fundamentalmente de la rehabilitación de personas con patologías motoras",
      "Portal": "https://www.hptu.org.co/subespecialidades-pediátricas.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 50,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Gastroenterología adulto",
      "Descripcion": "Especialidad médica que se ocupa de las enfermedades del aparato digestivo y órganos asociados, conformado por: esófago, estómago, hígado y vías biliares, páncreas, intestino delgado (duodeno, yeyuno, íleon), colon y recto.",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 51,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Geriatría",
      "Descripcion": "Especialidad médica que se ocupa de estudiar la vejez y todos los trastornos que la misma conlleva",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 52,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Ginecología",
      "Descripcion": "Especialidad médica que se ocupa del aparato genital femenino y sus enfermedades, incluidas las glándulas mamarias.",
      "Portal": "https://www.hptu.org.co/coloproctolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 53,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Hepatología adulto",
      "Descripcion": "Especialidad médica que se ocupa de las funciones y enfermedades del hígado y las vías biliares",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 54,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Infectología adulto",
      "Descripcion": "Especialidad médica del estudio, la prevención, el diagnóstico y el tratamiento de las enfermedades producidas por agentes infecciosos (bacterias, virus, hongos y parásitos)",
      "Portal": "https://www.hptu.org.co/dermatolog%C3%ADa-unidades-de-apoyo.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 55,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Medicina interna",
      "Descripcion": "Especialidad médica que se ocupa del estudio, diagnóstico y tratamiento de las enfermedades propias del adulto",
      "Portal": "https://www.hptu.org.co/cancerolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 56,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Medicina laboral y ocupacional",
      "Descripcion": "Especialidad médica que se ocupa del estudio de las enfermedades y los accidentes que se producen por causa o consecuencia de la actividad laboral",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 57,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Medicina general",
      "Descripcion": "Se ocupa del tratamiento de las patologías en su conjunto, sin consagrarse en ninguna especialidad.",
      "Portal": "https://www.hptu.org.co/subespecialidades-pediátricas.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 58,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Nefrología adultos",
      "Descripcion": "Especialidad médica que se ocupa de la anatomía, la fisiología y las enfermedades del riñón",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 59,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Neumología adulto",
      "Descripcion": "Especialidad médica que se ocupa del tratamiento y las enfermedades de los pulmones y las vías respiratorias.",
      "Portal": "https://www.hptu.org.co/gastroenterolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 60,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Neurocirugía",
      "Descripcion": "Especialidad médica que se ocupa de las enfermedades del sistema nervioso mediante operaciones quirúrgicas.",
      "Portal": "https://www.hptu.org.co/subespecialidades-pediátricas.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 61,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Neurología adulto",
      "Descripcion": "Especialidad médica que se ocupa de la anatomía, la fisiología y las enfermedades del sistema nervioso.",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 62,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Neuropsicología",
      "Descripcion": "Especialidad médica que se ocupa del estudio de las relaciones entre las funciones superiores y las estructuras cerebrales.",
      "Portal": "https://www.hptu.org.co/cancerolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 63,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Nutrición y dietética",
      "Descripcion": "Se ocupa del estudia de los regímenes alimenticios en la salud o en la enfermedad (dietoterapia)",
      "Portal": "https://www.hptu.org.co/subespecialidades-pediátricas.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 64,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Oftalmología",
      "Descripcion": "Especialidad médica que se ocupa del estudioy de las enfermades del ojo",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 65,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Ortopedia y traumatología",
      "Descripcion": "Especialidad médica encargada del estudio, tratamiento y prevención de las lesiones del aparato musculo esquelético",
      "Portal": "https://www.hptu.org.co/subespecialidades-pediátricas.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 66,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Otología y otoneurología",
      "Descripcion": "Especialidad médica que se ocupa del estudio de la audición, el equilibrio y todos los órganos que participan",
      "Portal": "https://www.hptu.org.co/infectolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 67,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Otorrinolaringología",
      "Descripcion": "Especialidad médica que se ocupa de la anatomía, la fisiología y las enfermedades del oído, la nariz y la garganta.",
      "Portal": "https://www.hptu.org.co/infectolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 68,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Pediatría",
      "Descripcion": "Especialidad médica que se ocupa del estudio del crecimiento y el desarrollo de los niños hasta la adolescencia, así como del tratamiento de sus enfermedades.",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 69,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Psicología",
      "Descripcion": "Se ocupa de los procesos mentales, las sensaciones, las percepciones y el comportamiento del ser humano, en relación con el medio ambiente físico y social que lo rodea",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 70,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Psiquiatría",
      "Descripcion": "Especialidad médica que se ocupa del estudio, el diagnóstico, el tratamiento y la prevención de las enfermedades mentales de carácter orgánico y no orgánico",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 71,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Reumatología adulto",
      "Descripcion": "Especialidad médica que se ocupa del manejo de los trastornos médicos (no los quirúrgicos) del aparato locomotor y del tejido conectivo",
      "Portal": "https://www.hptu.org.co/medicina-interna.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 72,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Toxicología clínica",
      "Descripcion": "Especialidad médica que se ocupa del estudio y los efectos de los productos tóxicos o venenosos sobre el organismo.",
      "Portal": "https://www.hptu.org.co/nefrolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 73,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Urología",
      "Descripcion": "Especialidad médica que se ocupa la anatomía, la fisiología y las enfermedades del aparato urinario y, en el hombre, del aparato genital",
      "Portal": "https://www.hptu.org.co/subespecialidades-pediátricas.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 74,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Cardiología pediátrica",
      "Descripcion": "Especialidad médica que se ocupa de las enfermedades congénitas y adquiridas del corazón en los niños y adolescentes",
      "Portal": "https://www.hptu.org.co/neumolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 75,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Cirugía infantil",
      "Descripcion": "Especialidad quirúrgica que se ocupa del diagnóstico, cuidado preoperatorio, operación y manejo postoperatorio de los problemas que presentan en los niños y adolescentes",
      "Portal": "https://www.hptu.org.co/subespecialidades-pediátricas.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 76,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Endocrinología pediátrica",
      "Descripcion": "Especialidad médica que se ocupa del diagnóstico, tratamiento y supervisión de trastornos hormonales que presentan en los niños y adolescentes",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 77,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Gastroenterología infantil",
      "Descripcion": "Especialidad médica que se ocupa de las enfermedades del aparato digestivo y órganos asociados, conformado por: esófago, estómago, hígado y vías biliares, páncreas, intestino delgado (duodeno, yeyuno, íleon), colon y recto, que presentan en los niños y adolescentes",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 78,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Genética pediátrica",
      "Descripcion": "Especialidad médica que se ocupa de los trastornos del desarrollo normal de los individuos, tanto física como internamente, además de alteraciones conductuales e intelectuales.",
      "Portal": "https://www.hptu.org.co/subespecialidades-pediátricas.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 79,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Infectología pediátrica",
      "Descripcion": "Especialidad médica que se ocupa del estudio, la prevención, el diagnóstico y el tratamiento de las enfermedades producidas por agentes infecciosos",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 80,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Medicina crítica y cuidado intensivo",
      "Descripcion": "Especialidad médica que se ocupa del suministro de soporte vital o de soporte a los sistemas orgánicos en los pacientes que están críticamente enfermos",
      "Portal": "https://www.hptu.org.co/nutrición.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 81,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Nefrología pediátrica",
      "Descripcion": "Especialidad médica que se se ocupa del estudio de la estructura y la función renal, tanto en la salud como en la enfermedad, incluyendo la prevención y tratamiento de las enfermedades renales  en los niños y adolescentes",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 82,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Neumología pediátrica",
      "Descripcion": "Especialidad médica que se ocupa del diagnóstico y tratamiento de las enfermedades y trastornos de los pulmones en los niños  y adolescentes",
      "Portal": "https://www.hptu.org.co/cancerolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 83,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Neurología pediátrica",
      "Descripcion": "Especialidad médica que se ocupa de diagnosticar y tratar todas aquellas patologías y trastornos relacionados con el sistema nervioso central y nervios periféricos en los niños y adolescentes",
      "Portal": "https://www.hptu.org.co/cancerolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 84,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Reumatología infantil",
      "Descripcion": "Especialidad médica que se ocupa del diagnóstico y tratamiento de las enfermedades inflamatorias del aparato locomotor y otras patologías de origen autoinmune en niños y adolescentes",
      "Portal": "https://www.hptu.org.co/cancerolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 85,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Cirugía de mama y tumores de tejidos blandos",
      "Descripcion": "Especialidad quirúrgica que se ocupa del estudio de las glándulas mamarias.",
      "Portal": "https://www.hptu.org.co/subespecialidades-pediátricas.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 86,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Cirugía cabeza y cuello",
      "Descripcion": "Especialidad quirúrgica encargada del manejo de enfermedades localizadas en cabeza y cuello.",
      "Portal": "https://www.hptu.org.co/ortopedia.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 87,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Dolor y cuidado paliativo",
      "Descripcion": "Especialidad médica que se ocupa de las atenciones, cuidados y tratamientos médicos farmacológicos que se dan a los enfermos en fase avanzada y enfermedad terminal.",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 88,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Ginecología oncológica",
      "Descripcion": "Especialidad médica que se ocupa del cuidado de la mujer con cáncer genital: cáncer de cuello de útero, cáncer de endometrio o de cuerpo de útero, cáncer de ovario, cáncer de vulva o de vagina",
      "Portal": "https://www.hptu.org.co/pediatr%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 89,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Hematología adulto",
      "Descripcion": "Especialidad médica que se ocupa del estudia de los elementos inmunológicos de la sangre y las enfermedades que se manifiestan por la alteración de estos elementos",
      "Portal": "https://www.hptu.org.co/psicolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 90,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Hematología pediátrica",
      "Descripcion": "Especialidad médica que se ocupa del estudia de los elementos inmunológicos de la sangre y las enfermedades que se manifiestan por la alteración de estos elementos en niños y adolescentes",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 91,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Neurología oncológica",
      "Descripcion": "Especialidad médica que se ocupa del tratamiento de los trastornos del sistema nervioso en niños y adolescentes",
      "Portal": "https://www.hptu.org.co/cancerolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 92,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Oncología clínica adulto",
      "Descripcion": "Especialidad médica que se ocupa del estudio y tratamiento de las neoplasias; tumores benignos y malignos, pero con especial atención a los tumores malignos o cáncer",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 93,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Oncología clínica pediátrica",
      "Descripcion": "Especialidad médica que se ocupa del estudio y tratamiento de las neoplasias; tumores benignos y malignos, pero con especial atención a los tumores malignos o cáncer en niños y adolescentes",
      "Portal": "https://www.hptu.org.co/reumatolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 94,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Radioterapia",
      "Descripcion": "Se trata de una forma de tratamiento basada en el empleo de radiaciones ionizantes (rayos X o radiactividad, la que incluye los rayos gamma y las partículas alfa).",
      "Portal": "https://www.hptu.org.co/reumatolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 95,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Urología oncológica",
      "Descripcion": "Especialidad médica que se ocupa  del diagnóstico y tratamiento de los distintos tipos de cáncer que pueden aparecer en el sistema urinario",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 96,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Consulta",
      "Nombre": "Ortopedia oncológica",
      "Descripcion": "Especialidad médica que se ocupa de los tumores en huesos y en tejidos blandos que no sean de piel, en específico los musculo esqueléticos",
      "Portal": "https://www.hptu.org.co/urolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 10"
    },
    {
      "id": 97,
      "Grupo": "Servicio de Urgencias",
      "Subgrupo": "Urgencias",
      "Nombre": "Servicio de urgencias",
      "Descripcion": "Atención de urgencias y emergencias para pacientes adultos y pediátricos.",
      "Portal": "https://www.hptu.org.co/urgencias.html",
      "Horario_atencion": "24 horas. 7 días a la semana",
      "Horario_visitas": "7:00 a.m. a 8:00 a.m.. 11:00 a.m. a 12:00 m.. 3:00 p.m. a 4:00 p.m.. 6:00 p.m. a 7:00 p.m.",
      "Ubicacion": "Torre A piso 2 y 3"
    },
    {
      "id": 98,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Diagnóstico cardiovascular",
      "Descripcion": "Exámenes de diagnóstico que se realizan para entender e identificar mejor las enfermedades cardiovasculares",
      "Portal": "https://www.hptu.org.co/cardiolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 99,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Endoscopia digestiva",
      "Descripcion": "Consiste en la realización de estudios para visualizar y en ocasiones tratar patologías del tubo digestivo y tracto gastrointestinal, con ayuda de un endoscopio",
      "Portal": "https://www.hptu.org.co/gastroenterolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 100,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Neumología - fibrobroncoscopia",
      "Descripcion": "Método de exploración e inspección directa de la laringe y el árbol traqueobronquial con un tubo largo, delgado y flexible de fibra de vidrio cómo medio óptico, llamado fibrobroncoscopio.",
      "Portal": "https://www.hptu.org.co/neumolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 101,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Radiología",
      "Nombre": "Hemodinamia",
      "Descripcion": "Estudio anatómico y funcional del corazón mediante la introducción de catéteres finos a través de las arterias de la ingle o del brazo",
      "Portal": "https://www.hptu.org.co/especialidades.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 102,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Laboratorio",
      "Nombre": "Laboratorio clínico",
      "Descripcion": "Lugar donde analizan muestras biológicas humanas que contribuyen al estudio, prevención, diagnóstico y tratamiento de las enfermedades",
      "Portal": "https://www.hptu.org.co/laboratorio.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 1"
    },
    {
      "id": 103,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Urología - litotripsia urológica",
      "Descripcion": "Procedimiento médico que utiliza ondas de choque para romper cálculos que se forman en el riñón, la vejiga o el uréter (el conducto que lleva la orina de los riñones a la vejiga)",
      "Portal": "https://www.hptu.org.co/urolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 104,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Cancerología",
      "Nombre": "Quimioterapia",
      "Descripcion": "Tratamiento con medicamentos para interrumpir la formación de células cancerosas, ya sea mediante su destrucción o al impedir su multiplicación",
      "Portal": "https://www.hptu.org.co/cancerolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso -1"
    },
    {
      "id": 105,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Radiología",
      "Nombre": "Radiología e imágenes diagnósticas",
      "Descripcion": "Generación de imágenes del interior del cuerpo mediante diferentes agentes físicos (rayos X, ultrasonidos, campos magnéticos, entre otros) y de utilizar estas imágenes para el diagnóstico y, en menor medida, para el pronóstico y el tratamiento de las enfermedades.",
      "Portal": "https://www.hptu.org.co/radiolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 106,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Cancerología",
      "Nombre": "Radioterapia",
      "Descripcion": "Especialidad clínica encargada del estudio y manejo de las radiaciones ionizantes como tratamiento para el cáncer y algunas condiciones benignas en contextos tanto curativos como paliativos.",
      "Portal": "https://www.hptu.org.co/cancerolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso -1"
    },
    {
      "id": 107,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Laboratorio",
      "Nombre": "Toma de muestras de laboratorio clínico",
      "Descripcion": "Procedimiento especializado que consiste en la obtención de uno o varios especimenes biológicos con el fin de encontrar la causa o factores que afectan la salud.",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 1"
    },
    {
      "id": 108,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Otros",
      "Nombre": "Transfusión sanguínea",
      "Descripcion": "Procedimiento que consiste en hacer pasar sangre o alguno de sus derivados de un donante a un receptor.",
      "Portal": "https://www.hptu.org.co/banco-de-sangre.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 1"
    },
    {
      "id": 109,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Otros",
      "Nombre": "Servicio farmacéutico",
      "Descripcion": "Servicios relacionados con medicamentos y dispositivos médicos",
      "Portal": "https://www.hptu.org.co/farmacia.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 1"
    },
    {
      "id": 110,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Radiología",
      "Nombre": "Medicina nuclear",
      "Descripcion": "Estudios de diagnóstico y tratamiento mediante la utilización de trazadores o radiofármacos.",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 111,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Laboratorio",
      "Nombre": "Laboratorio citologías cérvico - uterinas",
      "Descripcion": "Es un examen para detectar cáncer de cuello uterino.",
      "Portal": "https://www.hptu.org.co/laboratorio.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 1"
    },
    {
      "id": 112,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Laboratorio",
      "Nombre": "Laboratorio de patología",
      "Descripcion": "Servicio responsable del estudio histopatológico de las muestras de tejido tomadas de los pacientes con el objetivo de establecer un diagnóstico específico o en su defecto, contribuir a explicar la etiopatogenia de la enfermedad",
      "Portal": "https://www.hptu.org.co/laboratorio.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 1"
    },
    {
      "id": 113,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Radiología",
      "Nombre": "Ultrasonido (ecografía)",
      "Descripcion": "Procedimientos que uiliza ondas sonoras de alta frecuencia para observar órganos y estructuras al interior del cuerpo",
      "Portal": "https://www.hptu.org.co/radiolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 114,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Electrodiagnóstico",
      "Descripcion": "Diagnóstico de algunas enfermedades que se realiza mediante la aplicación de la electricidad",
      "Portal": "https://www.hptu.org.co/especialidades.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 115,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Terapia ocupacional",
      "Descripcion": "Se ocupa de la promoción de la salud y el bienestar a través de la ocupación",
      "Portal": "https://www.hptu.org.co/especialidades.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 116,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Terapia respiratoria",
      "Descripcion": "Conjunto de técnicas y procedimientos para el manejo de enfermedades respiratorias aplicables en adultos, pediátricos y neonatos, que al aplicarse coadyuvan al fortalecimiento y restauración de la función pulmonar mediante inhalaciones de medicamentos y con base en la humedad",
      "Portal": "https://www.hptu.org.co/especialidades.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 117,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Neumología laboratorio función pulmonar",
      "Descripcion": "Se encarga del tratamiento, prevención y estabilización de las diferentes enfermedades del aparato respiratorio o cualquiera que interfiera en su correcto funcionamiento, con el fin de mantener o mejorar la función respiratoria.",
      "Portal": "https://www.hptu.org.co/neumolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 118,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Laboratorio",
      "Nombre": "Laboratorio de histotecnología",
      "Descripcion": "Servicio donde se realizan los análisis de los tejidos",
      "Portal": "https://www.hptu.org.co/laboratorio.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre A piso 1"
    },
    {
      "id": 119,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Ecocardiografía",
      "Descripcion": "Unidad que presta servicios diagnósticos por imagen en forma no invasiva del corazón y los grandes vasos, para ofrecer una atención integral a las personas con sospecha de enfermedad cardiaca",
      "Portal": "https://www.hptu.org.co/cardiolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 120,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Radiología",
      "Nombre": "Electrofisiología, marcapasos y arritmias cardíacas",
      "Descripcion": "Procedimientos para el diagnóstico o tratamiento de los mecanismos, funciones, y desempeño, de las actividades eléctricas de las regiones específicas del corazón.",
      "Portal": "https://www.hptu.org.co/cardiolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 121,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Fisioterapia",
      "Descripcion": "Esta especialidad ofrece atención no farmacológica para el diagnóstico, prevención y tratamiento de síntomas de múltiples patologías agudas y crónicas de tipo osteomuscular",
      "Portal": "https://www.hptu.org.co/especialidades.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 122,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Fonoaudiología y/o terapia del lenguaje",
      "Descripcion": "En este servicios se manejan aspectos de la comunicación humana, con sus desórdenes y variaciones y los trastornos de la deglución o disfagia.",
      "Portal": "https://www.hptu.org.co/especialidades.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 123,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Alergología",
      "Descripcion": "Especialidad médica que se ocupa del diagnóstico y tratamiento de las enfermedades cuyo origen se encuentra enmarcado en una base alérgica",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 124,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Neurología",
      "Descripcion": "Especialidad médica que estudia la estructura, función y desarrollo del sistema nervioso (central, periférico y autónomo) y muscular en estado normal y patológico, utilizando diversas técnicas clínicas e instrumentales de estudio, diagnóstico y tratamiento",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 125,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Dermatología",
      "Descripcion": "Especialidad médica que se ocupa del diagnóstico, tratamiento y manejo de las enfermedades y desórdenes de la piel, pelo, uñas y mucosas",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 126,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Otorrinolaringología",
      "Descripcion": "Especialidad médica que se ocupa del manejo y tratamiento, tanto médico como quirúrgico, de pacientes con enfermedades y alteraciones del oído, nariz, garganta y estructuras relacionadas de la cabeza y del cuello",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 127,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Fisiatría",
      "Descripcion": "Especialidad médica que se encarga de la evaluación, tratamiento y seguimiento en pacientes con enfermedades del Sistema Muscular, Esquelético y Neurológico, que produzcan dolor y algún grado de limitación funcional, de tipo transitoria o permanente.",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 128,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Endocrinología",
      "Descripcion": "Especialidad médica que de ocupa del estudio y diagnóstico de las enfermedades que afectan las glándulas de secreción interna",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 129,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Urología",
      "Descripcion": "Especialidad médica quirúrgica de la medicina que maneja el sistema urinario y genital de hombres y mujeres. Esto incluye el manejo de las patologías de órganos como la vejiga, riñón, uréter, uretra, próstata, testículos, pene y muchas de las enfermedades vaginales en las damas",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 130,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Ginecología",
      "Descripcion": "Especialidad médica quirúrgica que se ocupa del cuidado de la salud femenina fuera del embarazo, es decir, todos los aspectos de la salud y enfermedad específicos de la mujer y, por tanto, relacionados con su sistema reproductivo o con su condición de género",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 131,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Audiología",
      "Descripcion": "Se encargan de diagnosticar y prevenir los problemas auditivos",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 132,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Radiología",
      "Nombre": "Tomografía",
      "Descripcion": "Es un examen no invasivo que utiliza un equipo de rayos X especial para tomar imágenes de las estructuras internas del cuerpo.",
      "Portal": "https://www.hptu.org.co/radiolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 133,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Radiología",
      "Nombre": "Resonancia magnética",
      "Descripcion": "Prueba diagnóstica con la que se obtiene imágenes del interior del cuerpo. Se basa en el procesamiento de ondas de radio que pasan por el paciente, el cual es sometido a un potente campo magnético.",
      "Portal": "https://www.hptu.org.co/radiolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 134,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Radiología",
      "Nombre": "Radiología convencional",
      "Descripcion": "Imagen de las estructuras internas del cuerpo producidos por la exposición a una fuente controlada de los rayos X y que se registra en una película fotográfica o en un sistema digital como un CD o disco duro que después puede verse en un ordenador.",
      "Portal": "https://www.hptu.org.co/radiolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 135,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Radiología",
      "Nombre": "Tomografía por emisión de positrones",
      "Descripcion": "Es un método de diagnóstico por imagen en el que se obtienen de forma secuencial imágenes de PET (siglas en inglés de tomografía por emisión de positrones) y CT (siglas en inglés de tomografía computarizada en un mismo equipo tomográfico PET-CT.",
      "Portal": "https://www.hptu.org.co/radiolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 136,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Radiología",
      "Nombre": "Intervencionismo corporal",
      "Descripcion": "Este tipo de exámenes diagnósticos y terapéuticos utilizan como guía diferentes equipos que permiten visualizar en tiempo real diversos órganos o estructuras vasculares. Son procedimientos mínimamente invasivos por cuanto se accede al sitio deseado con pequeñas agujas o catéteres a través de una pequeña incisión en la piel menor a 5 milímetros.",
      "Portal": "https://www.hptu.org.co/radiolog%C3%ADa.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 137,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Ayudas diagnósticas",
      "Nombre": "Chequeo ejecutivo",
      "Descripcion": "Evaluación médica acompañada de una serie de exámenes queen conjunto, pretenden detectar factores de riesgo o enfermedades de manera temprana para intervenirlas y evitar su influencia negativa sobre la salud",
      "Portal": "https://www.hptu.org.co/chequeos-ejecutivos.html",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso 2"
    },
    {
      "id": 138,
      "Grupo": "Servicios Ambulatorios",
      "Subgrupo": "Cancerología",
      "Nombre": "Procedimientos diagnósticos",
      "Descripcion": "Aspirado biopsia de médula ósea",
      "Portal": "",
      "Horario_atencion": "Lunes a viernes, diurno",
      "Horario_visitas": null,
      "Ubicacion": "Torre B piso -1"
    }
  ]